import { StyleSheet } from "react-native";
import { FONT_SIZES } from "../utils/fontSizes";

/**
 * Função que cria estilos dinâmicos baseados na escala de fonte
 */
export const createListarOcorrenciaStyles = (scaleFont) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
    },
    content: {
      flex: 1,
      padding: 20,
      marginBottom: 10,
    },
    selectionHeader: {
      backgroundColor: "#e3f2fd",
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#2196f3",
      flexDirection: "column",
    },
    selectionText: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#1976d2",
      fontWeight: "bold",
      marginBottom: 8,
    },
    selectionActions: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    selectionButton: {
      padding: 4,
    },
    selectAllText: {
      color: "#1976d2",
      fontWeight: "bold",
      fontSize: scaleFont(FONT_SIZES.md),
    },
    cancelSelectionText: {
      color: "#f44336",
      fontWeight: "bold",
      fontSize: scaleFont(FONT_SIZES.md),
    },
    placeholderSection: {
      alignItems: "center",
      paddingVertical: 30,
      backgroundColor: "#f8f8f8",
      borderRadius: 12,
      marginBottom: 20,
    },
    placeholderTitle: {
      fontSize: scaleFont(FONT_SIZES.xxxl),
      fontWeight: "bold",
      color: "#bc010c",
      marginTop: 15,
      marginBottom: 10,
    },
    placeholderText: {
      fontSize: scaleFont(FONT_SIZES.base),
      color: "#666",
      textAlign: "center",
      paddingHorizontal: 20,
    },
    contador: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#bc010c",
      fontWeight: "600",
      marginTop: 8,
    },
    exportHint: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#666",
      fontStyle: "italic",
      marginTop: 8,
      textAlign: "center",
    },
    filtroContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
      backgroundColor: "#f1f1f1",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: "#ddd",
    },
    filtroInput: {
      flex: 1,
      marginLeft: 8,
      fontSize: scaleFont(FONT_SIZES.base),
      color: "#333",
    },
    limparFiltro: {
      padding: 4,
    },
    dashboardButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#bc010c",
      padding: 12,
      borderRadius: 8,
      marginBottom: 16,
    },
    dashboardButtonText: {
      color: "#fff",
      fontSize: scaleFont(FONT_SIZES.base),
      fontWeight: "bold",
      marginLeft: 8,
    },
    ocorrenciaCard: {
      backgroundColor: "#f8f8f8",
      padding: 15,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: "#e1e1e1",
      position: "relative",
    },
    selectedOccurrenceCard: {
      backgroundColor: "#e3f2fd",
      borderColor: "#2196f3",
      borderWidth: 2,
    },
    selectionIndicator: {
      position: "absolute",
      top: 10,
      left: 10,
      zIndex: 1,
    },
    ocorrenciaContent: {
      flex: 1,
      marginLeft: 8,
    },
    ocorrenciaHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 10,
    },
    ocorrenciaTipo: {
      fontSize: scaleFont(FONT_SIZES.lg),
      fontWeight: "bold",
      color: "#333",
      flex: 1,
      marginRight: 8,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 15,
      minWidth: 80,
      alignItems: "center",
      alignSelf: "flex-start",
      marginLeft: "auto",
    },
    statusText: {
      color: "#fff",
      fontSize: scaleFont(FONT_SIZES.sm),
      fontWeight: "bold",
      textAlign: "center",
    },
    ocorrenciaDescricao: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#666",
      marginBottom: 8,
      lineHeight: 18,
    },
    ocorrenciaInfo: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 6,
    },
    ocorrenciaLocal: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#666",
      marginLeft: 6,
      flex: 1,
    },
    ocorrenciaHora: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#666",
      marginLeft: 6,
    },
    ocorrenciaDetalhes: {
      fontSize: scaleFont(FONT_SIZES.smMd),
      color: "#888",
      marginLeft: 6,
      fontStyle: "italic",
      flex: 1,
    },
    ocorrenciaData: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#999",
      marginLeft: 6,
    },
    semResultados: {
      alignItems: "center",
      paddingVertical: 40,
      paddingHorizontal: 20,
    },
    semResultadosText: {
      fontSize: scaleFont(FONT_SIZES.base),
      color: "#888",
      textAlign: "center",
      marginTop: 10,
      marginBottom: 20,
    },
    novaOcorrenciaButton: {
      backgroundColor: "#bc010c",
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
    },
    novaOcorrenciaButtonText: {
      color: "#fff",
      fontSize: scaleFont(FONT_SIZES.base),
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      backgroundColor: "white",
      borderRadius: 16,
      padding: 24,
      width: "80%",
      alignItems: "center",
    },
    modalTitle: {
      fontSize: scaleFont(FONT_SIZES.xl),
      fontWeight: "bold",
      marginBottom: 8,
      color: "#333",
    },
    modalSubtitle: {
      fontSize: scaleFont(FONT_SIZES.md),
      color: "#666",
      marginBottom: 8,
      textAlign: "center",
    },
    modalInfo: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#888",
      marginBottom: 24,
      textAlign: "center",
      fontStyle: "italic",
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 16,
    },
    modalButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 16,
      borderRadius: 8,
      marginHorizontal: 5,
    },
    csvButton: {
      backgroundColor: "#4CAF50",
    },
    pdfButton: {
      backgroundColor: "#f44336",
    },
    modalButtonText: {
      color: "white",
      fontWeight: "bold",
      marginLeft: 8,
    },
    cancelButton: {
      padding: 12,
    },
    cancelButtonText: {
      color: "#666",
      fontSize: scaleFont(FONT_SIZES.base),
    },
  });
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  content: {
    flex: 1,
    padding: 20,
    marginBottom: 10,
  },
  selectionHeader: {
    backgroundColor: "#e3f2fd",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#2196f3",
    flexDirection: "column",
  },
  selectionText: {
    fontSize: FONT_SIZES.md,
    color: "#1976d2",
    fontWeight: "bold",
    marginBottom: 8,
  },
  selectionActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  selectionButton: {
    padding: 4,
  },
  selectAllText: {
    color: "#1976d2",
    fontWeight: "bold",
    fontSize: FONT_SIZES.md,
  },
  cancelSelectionText: {
    color: "#f44336",
    fontWeight: "bold",
    fontSize: FONT_SIZES.md,
  },
  placeholderSection: {
    alignItems: "center",
    paddingVertical: 30,
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    marginBottom: 20,
  },
  placeholderTitle: {
    fontSize: FONT_SIZES.xxxl,
    fontWeight: "bold",
    color: "#bc010c",
    marginTop: 15,
    marginBottom: 10,
  },
  placeholderText: {
    fontSize: FONT_SIZES.base,
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 20,
  },
  contador: {
    fontSize: FONT_SIZES.md,
    color: "#bc010c",
    fontWeight: "600",
    marginTop: 8,
  },
  exportHint: {
    fontSize: FONT_SIZES.sm,
    color: "#666",
    fontStyle: "italic",
    marginTop: 8,
    textAlign: "center",
  },
  filtroContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    backgroundColor: "#f1f1f1",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  filtroInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: FONT_SIZES.base,
    color: "#333",
  },
  limparFiltro: {
    padding: 4,
  },
  dashboardButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#bc010c",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  dashboardButtonText: {
    color: "#fff",
    fontSize: FONT_SIZES.base,
    fontWeight: "bold",
    marginLeft: 8,
  },
  ocorrenciaCard: {
    backgroundColor: "#f8f8f8",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e1e1e1",
    position: "relative",
  },
  selectedOccurrenceCard: {
    backgroundColor: "#e3f2fd",
    borderColor: "#2196f3",
    borderWidth: 2,
  },
  selectionIndicator: {
    position: "absolute",
    top: 10,
    left: 10,
    zIndex: 1,
  },
  ocorrenciaContent: {
    flex: 1,
    marginLeft: 8,
  },
  ocorrenciaHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  ocorrenciaTipo: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
    marginRight: 8,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    minWidth: 80,
    alignItems: "center",
    alignSelf: "flex-start",
    marginLeft: "auto",
  },
  statusText: {
    color: "#fff",
    fontSize: FONT_SIZES.sm,
    fontWeight: "bold",
    textAlign: "center",
  },
  ocorrenciaDescricao: {
    fontSize: FONT_SIZES.md,
    color: "#666",
    marginBottom: 8,
    lineHeight: 18,
  },
  ocorrenciaInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  ocorrenciaLocal: {
    fontSize: FONT_SIZES.md,
    color: "#666",
    marginLeft: 6,
    flex: 1,
  },
  ocorrenciaHora: {
    fontSize: FONT_SIZES.md,
    color: "#666",
    marginLeft: 6,
  },
  ocorrenciaDetalhes: {
    fontSize: FONT_SIZES.smMd,
    color: "#888",
    marginLeft: 6,
    fontStyle: "italic",
    flex: 1,
  },
  ocorrenciaData: {
    fontSize: FONT_SIZES.sm,
    color: "#999",
    marginLeft: 6,
  },
  semResultados: {
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  semResultadosText: {
    fontSize: FONT_SIZES.base,
    color: "#888",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  novaOcorrenciaButton: {
    backgroundColor: "#bc010c",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  novaOcorrenciaButtonText: {
    color: "#fff",
    fontSize: FONT_SIZES.base,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 24,
    width: "80%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
  },
  modalSubtitle: {
    fontSize: FONT_SIZES.md,
    color: "#666",
    marginBottom: 8,
    textAlign: "center",
  },
  modalInfo: {
    fontSize: FONT_SIZES.sm,
    color: "#888",
    marginBottom: 24,
    textAlign: "center",
    fontStyle: "italic",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 16,
  },
  modalButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  csvButton: {
    backgroundColor: "#4CAF50",
  },
  pdfButton: {
    backgroundColor: "#f44336",
  },
  modalButtonText: {
    color: "white",
    fontWeight: "bold",
    marginLeft: 8,
  },
  cancelButton: {
    padding: 12,
  },
  cancelButtonText: {
    color: "#666",
    fontSize: FONT_SIZES.base,
  },
});

export default styles;