import { StyleSheet } from "react-native";
import { FONT_SIZES } from "../utils/fontSizes";

/**
 * Função que cria estilos dinâmicos baseados na escala de fonte
 */
export const createNovaOcorrenciaStyles = (scaleFont) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f5f5f5",
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 16,
      paddingBottom: 30,
    },
    row: {
      flexDirection: "row",
    },
    flex1: {
      flex: 1,
    },
    marginLeft: {
      marginLeft: 8,
    },
    buttonGroup: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 8,
    },
    optionButton: {
      flex: 1,
      padding: 12,
      borderRadius: 8,
      alignItems: "center",
      marginHorizontal: 4,
      borderWidth: 2,
    },
    optionButtonSelected: {
      backgroundColor: "#bc010c",
      borderColor: "#bc010c",
    },
    optionButtonUnselected: {
      backgroundColor: "#f8f8f8",
      borderColor: "#ccc",
    },
    optionButtonText: {
      fontSize: scaleFont(FONT_SIZES.base),
      fontWeight: "bold",
    },
    optionButtonTextSelected: {
      color: "white",
    },
    optionButtonTextUnselected: {
      color: "#666",
    },
    textArea: {
      height: 80,
      textAlignVertical: "top",
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
      marginBottom: 10,
    },
    button: {
      flex: 1,
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
      marginHorizontal: 6,
    },
    clearButton: {
      backgroundColor: "#6c757d",
    },
    saveButton: {
      backgroundColor: "#bc010c",
    },
    disabledButton: {
      backgroundColor: "#cccccc",
    },
    buttonText: {
      color: "white",
      fontWeight: "bold",
      fontSize: scaleFont(FONT_SIZES.base),
    },
    requiredNote: {
      alignItems: "center",
      marginBottom: 20,
    },
    requiredText: {
      color: "#666",
      fontSize: scaleFont(FONT_SIZES.sm),
      fontStyle: "italic",
      marginBottom: 4,
    },
    pickerContainer: {
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      backgroundColor: "#fff",
      overflow: "hidden",
      marginTop: 4,
    },
    picker: {
      height: 56,
      color: "#333",
      fontSize: scaleFont(FONT_SIZES.base),
      paddingHorizontal: 8,
    },
    charCounter: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#666",
      textAlign: "right",
      marginTop: 4,
    },
    autoGeneratedInput: {
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      padding: 12,
      fontSize: scaleFont(FONT_SIZES.base),
      backgroundColor: "#f9f9f9",
    },
    helperText: {
      fontSize: scaleFont(FONT_SIZES.xs),
      color: "#666",
      fontStyle: "italic",
      marginTop: 4,
    },
    photoSection: {
      marginVertical: 10,
    },
    cameraButton: {
      borderWidth: 2,
      borderColor: "#bc010c",
      borderStyle: "dashed",
      borderRadius: 12,
      backgroundColor: "#f9f9f9",
      padding: 20,
    },
    cameraButtonContent: {
      alignItems: "center",
    },
    cameraButtonText: {
      fontSize: scaleFont(FONT_SIZES.base),
      fontWeight: "600",
      color: "#bc010c",
      textAlign: "center",
      marginBottom: 5,
    },
    cameraButtonSubtext: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#666",
      textAlign: "center",
    },
    photoPreviewContainer: {
      alignItems: "center",
      backgroundColor: "#f8f8f8",
      borderRadius: 12,
      padding: 15,
    },
    photoPreview: {
      width: "100%",
      height: 250,
      borderRadius: 8,
      marginBottom: 10,
      backgroundColor: "#e0e0e0",
    },
    photoInfo: {
      fontSize: scaleFont(FONT_SIZES.sm),
      color: "#666",
      marginBottom: 15,
      textAlign: "center",
    },
    photoActions: {
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
    },
    photoButton: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
      minWidth: 120,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
    },
    retakeButton: {
      backgroundColor: "#bc010c",
    },
    removeButton: {
      backgroundColor: "#6c757d",
    },
    photoButtonText: {
      color: "white",
      fontWeight: "600",
      fontSize: scaleFont(FONT_SIZES.md),
      marginLeft: 5,
    },
    locationButtonContainer: {
      marginBottom: 16,
      alignItems: 'center',
    },
    locationButton: {
      backgroundColor: '#bc010c',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 200,
    },
    locationButtonDisabled: {
      backgroundColor: '#cccccc',
    },
    locationButtonText: {
      color: '#FFFFFF',
      fontSize: scaleFont(FONT_SIZES.base),
      fontWeight: '600',
      marginLeft: 8,
    },
    locationErrorText: {
      color: '#ff3b30',
      fontSize: scaleFont(FONT_SIZES.sm),
      marginTop: 4,
      textAlign: 'center',
    },
  });
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 30,
  },
  row: {
    flexDirection: "row",
  },
  flex1: {
    flex: 1,
  },
  marginLeft: {
    marginLeft: 8,
  },
  buttonGroup: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  optionButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginHorizontal: 4,
    borderWidth: 2,
  },
  optionButtonSelected: {
    backgroundColor: "#bc010c",
    borderColor: "#bc010c",
  },
  optionButtonUnselected: {
    backgroundColor: "#f8f8f8",
    borderColor: "#ccc",
  },
  optionButtonText: {
    fontSize: FONT_SIZES.base,
    fontWeight: "bold",
  },
  optionButtonTextSelected: {
    color: "white",
  },
  optionButtonTextUnselected: {
    color: "#666",
  },
  textArea: {
    height: 80,
    textAlignVertical: "top",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 10,
  },
  button: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginHorizontal: 6,
  },
  clearButton: {
    backgroundColor: "#6c757d",
  },
  saveButton: {
    backgroundColor: "#bc010c",
  },
  disabledButton: {
    backgroundColor: "#cccccc",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: FONT_SIZES.base,
  },
  requiredNote: {
    alignItems: "center",
    marginBottom: 20,
  },
  requiredText: {
    color: "#666",
    fontSize: FONT_SIZES.sm,
    fontStyle: "italic",
    marginBottom: 4,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    backgroundColor: "#fff",
    overflow: "hidden",
    marginTop: 4,
  },
  picker: {
    height: 56,
    color: "#333",
    fontSize: FONT_SIZES.base,
    paddingHorizontal: 8,
  },
  charCounter: {
    fontSize: FONT_SIZES.sm,
    color: "#666",
    textAlign: "right",
    marginTop: 4,
  },
  autoGeneratedInput: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 12,
    fontSize: FONT_SIZES.base,
    backgroundColor: "#f9f9f9",
  },
  helperText: {
    fontSize: FONT_SIZES.xs,
    color: "#666",
    fontStyle: "italic",
    marginTop: 4,
  },
  photoSection: {
    marginVertical: 10,
  },
  cameraButton: {
    borderWidth: 2,
    borderColor: "#bc010c",
    borderStyle: "dashed",
    borderRadius: 12,
    backgroundColor: "#f9f9f9",
    padding: 20,
  },
  cameraButtonContent: {
    alignItems: "center",
  },
  cameraButtonText: {
    fontSize: FONT_SIZES.base,
    fontWeight: "600",
    color: "#bc010c",
    textAlign: "center",
    marginBottom: 5,
  },
  cameraButtonSubtext: {
    fontSize: FONT_SIZES.sm,
    color: "#666",
    textAlign: "center",
  },
  photoPreviewContainer: {
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    padding: 15,
  },
  photoPreview: {
    width: "100%",
    height: 250,
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: "#e0e0e0",
  },
  photoInfo: {
    fontSize: FONT_SIZES.sm,
    color: "#666",
    marginBottom: 15,
    textAlign: "center",
  },
  photoActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  photoButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 120,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  retakeButton: {
    backgroundColor: "#bc010c",
  },
  removeButton: {
    backgroundColor: "#6c757d",
  },
  photoButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: FONT_SIZES.md,
    marginLeft: 5,
  },
  locationButtonContainer: {
    marginBottom: 16,
    alignItems: 'center',
  },
  locationButton: {
    backgroundColor: '#bc010c',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 200,
  },
  locationButtonDisabled: {
    backgroundColor: '#cccccc',
  },
  locationButtonText: {
    color: '#FFFFFF',
    fontSize: FONT_SIZES.base,
    fontWeight: '600',
    marginLeft: 8,
  },
  locationErrorText: {
    color: '#ff3b30',
    fontSize: FONT_SIZES.sm,
    marginTop: 4,
    textAlign: 'center',
  },
});

export default styles;